Require xlock in grml-lock if DISPLAY is set. [Closes: issue768]

diff --git a/usr_bin/grml-lock b/usr_bin/grml-lock
--- a/usr_bin/grml-lock
+++ b/usr_bin/grml-lock
@@ -10,10 +10,10 @@ PN="$0"
 
 if [ -r /etc/grml/script-functions ] ; then
    . /etc/grml/script-functions
-   if [ -x /usr/bin/X ] ; then
-      check4progs vlock xlock sudo chpasswd dialog || { echo "Sorry, can't continue. Exiting.">&2 ; exit 1 }
-   else
+   if [ -z "$DISPLAY" ] ; then
       check4progs vlock sudo chpasswd dialog || { echo "Sorry, can't continue. Exiting.">&2 ; exit 1 }
+  else
+      check4progs xlock sudo chpasswd dialog || { echo "Sorry, can't continue. Exiting.">&2 ; exit 1 }
    fi
 fi
 
