grml-chroot: mount /dev/pts as devpts inside chroot
Fixes:

| E: Can not write log (Is /dev/pts mounted?) - posix_openpt (2: No such file or directory)

Closes grml/grml#53

diff --git a/usr_sbin/grml-chroot b/usr_sbin/grml-chroot
--- a/usr_sbin/grml-chroot
+++ b/usr_sbin/grml-chroot
@@ -55,7 +55,8 @@ function mountit
 
 function umount_all
 {
-    for i in $MOUNTED_; do
+    local reverse=$(echo $MOUNTED_ | awk '{ for (i=NF; i>1; i--) printf("%s ",$i); print $1; }')
+    for i in $reverse; do
         umount "${DEST_}/$i"
     done
 }
@@ -78,6 +79,10 @@ if (( $# < 1 )); then
     die "Wrong number of arguments."
 fi
 
+if ! which awk >/dev/null 2>&1 ; then
+  die "No awk binary found, required for execution."
+fi
+
 DEST_="$1"; shift
 
 if [ ! -d "$DEST_" ]; then
@@ -88,6 +93,7 @@ fi
 mountit "proc"  "proc"
 mountit "sysfs" "sys"
 mountit "/dev"   "dev"   "--bind"
+mountit "devpts" "dev/pts"
 
 WROTE_DEBIAN_CHROOT=""
 if [ ! -f "$DEST_"/etc/debian_chroot ]; then
